source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HaidoraNetworkHessian_Example', :exclusive => true do
  pod "HaidoraNetworkHessian", :path => "../"
end

target 'HaidoraNetworkHessian_Tests', :exclusive => true do
  pod "HaidoraNetworkHessian", :path => "../"

  
end
